# This is a basic workflow that is manually triggered

name: Test secrets

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on: workflow_dispatch

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "greet"
  greet:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Runs a single command using the runners shell
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: "10.x"
      - name: Create .env
        env: # Set the secret as an input
          secret_texts: ${{ secrets.MANY_VARS }}
        run: |
          echo "$secret_texts" > .env
      - name: Run index
        run: |
          node index.js
